apiVersion: v1
kind: Pod
metadata:
  name: aws-test
  namespace: site
spec:
  containers:
    - name: aws-cli
      image: amazon/aws-cli
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      command: ["aws", "s3", "ls"]
      envFrom:
        - secretRef:
            name: "aws-credentials"
# aws-credentials create secret terminal command

# kubectl create secret generic aws-credentials \
#   --from-literal=AWS_ACCESS_KEY_ID=... \
#   --from-literal=AWS_SECRET_ACCESS_KEY=...
