version: "3"

services:
  webapi:
    build:
      context: .
    pull_policy: always
    ports:
      - "8080:8000"
    networks:
      - web-network
    depends_on:
      - redis

  redis:
    image: redis:7.0.11
    ports:
      - "6379:6379"
    networks:
      - web-network

networks:
  web-network: {}
